[server]
runOnSave = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"